name: "Integration demo"
run-name: "Integration demo run"

on:
    push:
        branches:
            - main

jobs:
    first_install_python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
               python-version: '3.13'
            - run: python sendmail.py
            